#ifndef PERSISTENCIA_GLOBAL_H
#define PERSISTENCIA_GLOBAL_H

#include <QtCore/qglobal.h>



#if defined(PERSISTENCIA_LIBRARY)
#  define PERSISTENCIASHARED_EXPORT Q_DECL_EXPORT
#else
#  define PERSISTENCIASHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PERSISTENCIA_GLOBAL_H
