#ifndef MODULOCATALOGO_GLOBAL_H
#define MODULOCATALOGO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULOCATALOGO_LIBRARY)
#  define MODULOCATALOGOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULOCATALOGOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULOCATALOGO_GLOBAL_H
