#############################################################################
# Makefile for building: SistemaInventario
# Generated by qmake (2.01a) (Qt 4.5.2) on: lun 5. oct 16:21:44 2009
# Project:  SistemaInventario.pro
# Template: subdirs
# Command: c:\Qt\2009.03\qt\bin\qmake.exe -spec ..\..\..\..\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o Makefile SistemaInventario.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\Qt\2009.03\qt\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-ModuloContable \
		sub-SistemaInventarioBCUES \
		sub-ModuloCatalogo \
		sub-libncreport

ModuloContable\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ModuloContable\ $(MKDIR) ModuloContable\ 
	cd ModuloContable\ && $(QMAKE) ModuloContable.pro -spec c:\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o $(MAKEFILE)
sub-ModuloContable-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ModuloContable\ $(MKDIR) ModuloContable\ 
	cd ModuloContable\ && $(QMAKE) ModuloContable.pro -spec c:\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o $(MAKEFILE)
sub-ModuloContable: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE)
sub-ModuloContable-make_default: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) 
sub-ModuloContable-make_first: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) first
sub-ModuloContable-all: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) all
sub-ModuloContable-clean: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) clean
sub-ModuloContable-distclean: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) distclean
sub-ModuloContable-install_subtargets: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) install
sub-ModuloContable-uninstall_subtargets: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) uninstall
SistemaInventarioBCUES\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) SistemaInventarioBCUES\ $(MKDIR) SistemaInventarioBCUES\ 
	cd SistemaInventarioBCUES\ && $(QMAKE) SistemaInventarioBCUES.pro -spec c:\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o $(MAKEFILE)
sub-SistemaInventarioBCUES-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) SistemaInventarioBCUES\ $(MKDIR) SistemaInventarioBCUES\ 
	cd SistemaInventarioBCUES\ && $(QMAKE) SistemaInventarioBCUES.pro -spec c:\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o $(MAKEFILE)
sub-SistemaInventarioBCUES: SistemaInventarioBCUES\$(MAKEFILE) FORCE
	cd SistemaInventarioBCUES\ && $(MAKE) -f $(MAKEFILE)
sub-SistemaInventarioBCUES-make_default: SistemaInventarioBCUES\$(MAKEFILE) FORCE
	cd SistemaInventarioBCUES\ && $(MAKE) -f $(MAKEFILE) 
sub-SistemaInventarioBCUES-make_first: SistemaInventarioBCUES\$(MAKEFILE) FORCE
	cd SistemaInventarioBCUES\ && $(MAKE) -f $(MAKEFILE) first
sub-SistemaInventarioBCUES-all: SistemaInventarioBCUES\$(MAKEFILE) FORCE
	cd SistemaInventarioBCUES\ && $(MAKE) -f $(MAKEFILE) all
sub-SistemaInventarioBCUES-clean: SistemaInventarioBCUES\$(MAKEFILE) FORCE
	cd SistemaInventarioBCUES\ && $(MAKE) -f $(MAKEFILE) clean
sub-SistemaInventarioBCUES-distclean: SistemaInventarioBCUES\$(MAKEFILE) FORCE
	cd SistemaInventarioBCUES\ && $(MAKE) -f $(MAKEFILE) distclean
sub-SistemaInventarioBCUES-install_subtargets: SistemaInventarioBCUES\$(MAKEFILE) FORCE
	cd SistemaInventarioBCUES\ && $(MAKE) -f $(MAKEFILE) install
sub-SistemaInventarioBCUES-uninstall_subtargets: SistemaInventarioBCUES\$(MAKEFILE) FORCE
	cd SistemaInventarioBCUES\ && $(MAKE) -f $(MAKEFILE) uninstall
ModuloCatalogo\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ModuloCatalogo\ $(MKDIR) ModuloCatalogo\ 
	cd ModuloCatalogo\ && $(QMAKE) ModuloCatalogo.pro -spec c:\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o $(MAKEFILE)
sub-ModuloCatalogo-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ModuloCatalogo\ $(MKDIR) ModuloCatalogo\ 
	cd ModuloCatalogo\ && $(QMAKE) ModuloCatalogo.pro -spec c:\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o $(MAKEFILE)
sub-ModuloCatalogo: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE)
sub-ModuloCatalogo-make_default: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) 
sub-ModuloCatalogo-make_first: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) first
sub-ModuloCatalogo-all: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) all
sub-ModuloCatalogo-clean: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) clean
sub-ModuloCatalogo-distclean: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) distclean
sub-ModuloCatalogo-install_subtargets: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) install
sub-ModuloCatalogo-uninstall_subtargets: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) uninstall
libncreport\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libncreport\ $(MKDIR) libncreport\ 
	cd libncreport\ && $(QMAKE) libncreport.pro -spec c:\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o $(MAKEFILE)
sub-libncreport-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libncreport\ $(MKDIR) libncreport\ 
	cd libncreport\ && $(QMAKE) libncreport.pro -spec c:\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o $(MAKEFILE)
sub-libncreport: libncreport\$(MAKEFILE) FORCE
	cd libncreport\ && $(MAKE) -f $(MAKEFILE)
sub-libncreport-make_default: libncreport\$(MAKEFILE) FORCE
	cd libncreport\ && $(MAKE) -f $(MAKEFILE) 
sub-libncreport-make_first: libncreport\$(MAKEFILE) FORCE
	cd libncreport\ && $(MAKE) -f $(MAKEFILE) first
sub-libncreport-all: libncreport\$(MAKEFILE) FORCE
	cd libncreport\ && $(MAKE) -f $(MAKEFILE) all
sub-libncreport-clean: libncreport\$(MAKEFILE) FORCE
	cd libncreport\ && $(MAKE) -f $(MAKEFILE) clean
sub-libncreport-distclean: libncreport\$(MAKEFILE) FORCE
	cd libncreport\ && $(MAKE) -f $(MAKEFILE) distclean
sub-libncreport-install_subtargets: libncreport\$(MAKEFILE) FORCE
	cd libncreport\ && $(MAKE) -f $(MAKEFILE) install
sub-libncreport-uninstall_subtargets: libncreport\$(MAKEFILE) FORCE
	cd libncreport\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: SistemaInventario.pro  ../../../../Qt/2009.03/qt/mkspecs/win32-g++/qmake.conf ../../../../Qt/2009.03/qt/mkspecs/qconfig.pri \
		../../../../Qt/2009.03/qt/mkspecs/features/qt_functions.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/qt_config.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/default_pre.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/win32/default_pre.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/debug.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/debug_and_release.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/default_post.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/win32/default_post.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/win32/rtti.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/win32/exceptions.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/win32/stl.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/shared.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/warn_on.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/qt.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/win32/thread.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/moc.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/win32/windows.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/resources.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/uic.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/yacc.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/lex.prf \
		../../../../Qt/2009.03/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ..\..\..\..\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o Makefile SistemaInventario.pro
..\..\..\..\Qt\2009.03\qt\mkspecs\qconfig.pri:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\qt_functions.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\qt_config.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\default_pre.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\win32\default_pre.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\debug.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\debug_and_release.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\default_post.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\win32\default_post.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\win32\rtti.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\win32\exceptions.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\win32\stl.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\shared.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\warn_on.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\qt.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\win32\thread.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\moc.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\win32\windows.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\resources.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\uic.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\yacc.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\lex.prf:
..\..\..\..\Qt\2009.03\qt\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ..\..\..\..\Qt\2009.03\qt\mkspecs\win32-g++ -win32 -o Makefile SistemaInventario.pro

qmake_all: sub-ModuloContable-qmake_all sub-SistemaInventarioBCUES-qmake_all sub-ModuloCatalogo-qmake_all sub-libncreport-qmake_all FORCE

make_default: sub-ModuloContable-make_default sub-SistemaInventarioBCUES-make_default sub-ModuloCatalogo-make_default sub-libncreport-make_default FORCE
make_first: sub-ModuloContable-make_first sub-SistemaInventarioBCUES-make_first sub-ModuloCatalogo-make_first sub-libncreport-make_first FORCE
all: sub-ModuloContable-all sub-SistemaInventarioBCUES-all sub-ModuloCatalogo-all sub-libncreport-all FORCE
clean: sub-ModuloContable-clean sub-SistemaInventarioBCUES-clean sub-ModuloCatalogo-clean sub-libncreport-clean FORCE
distclean: sub-ModuloContable-distclean sub-SistemaInventarioBCUES-distclean sub-ModuloCatalogo-distclean sub-libncreport-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-ModuloContable-install_subtargets sub-SistemaInventarioBCUES-install_subtargets sub-ModuloCatalogo-install_subtargets sub-libncreport-install_subtargets FORCE
uninstall_subtargets: sub-ModuloContable-uninstall_subtargets sub-SistemaInventarioBCUES-uninstall_subtargets sub-ModuloCatalogo-uninstall_subtargets sub-libncreport-uninstall_subtargets FORCE

sub-ModuloContable-sub_Debug: ModuloContable\$(MAKEFILE)
	cd ModuloContable\ && $(MAKE) debug
sub-SistemaInventarioBCUES-sub_Debug: SistemaInventarioBCUES\$(MAKEFILE)
	cd SistemaInventarioBCUES\ && $(MAKE) debug
sub-ModuloCatalogo-sub_Debug: ModuloCatalogo\$(MAKEFILE)
	cd ModuloCatalogo\ && $(MAKE) debug
sub-libncreport-sub_Debug: libncreport\$(MAKEFILE)
	cd libncreport\ && $(MAKE) debug
debug: sub-ModuloContable-sub_Debug sub-SistemaInventarioBCUES-sub_Debug sub-ModuloCatalogo-sub_Debug sub-libncreport-sub_Debug

sub-ModuloContable-sub_Release: ModuloContable\$(MAKEFILE)
	cd ModuloContable\ && $(MAKE) release
sub-SistemaInventarioBCUES-sub_Release: SistemaInventarioBCUES\$(MAKEFILE)
	cd SistemaInventarioBCUES\ && $(MAKE) release
sub-ModuloCatalogo-sub_Release: ModuloCatalogo\$(MAKEFILE)
	cd ModuloCatalogo\ && $(MAKE) release
sub-libncreport-sub_Release: libncreport\$(MAKEFILE)
	cd libncreport\ && $(MAKE) release
release: sub-ModuloContable-sub_Release sub-SistemaInventarioBCUES-sub_Release sub-ModuloCatalogo-sub_Release sub-libncreport-sub_Release

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

