#############################################################################
# Makefile for building: SI-BCUES
# Generated by qmake (2.01a) (Qt 4.6.3) on: Lun 19. Jul 20:04:08 2010
# Project:  SI-BCUES.pro
# Template: subdirs
# Command: c:\qt\2010.04\qt\bin\qmake.exe -spec ..\..\..\..\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o Makefile SI-BCUES.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:\qt\2010.04\qt\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
SUBTARGETS    =  \
		sub-Persistencia \
		sub-Basico \
		sub-ModuloInventario \
		sub-ModuloCatalogo \
		sub-ModuloContable \
		sub-SIBCUES-GUI

Persistencia\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Persistencia\ $(MKDIR) Persistencia\ 
	cd Persistencia\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\Persistencia\Persistencia.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-Persistencia-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Persistencia\ $(MKDIR) Persistencia\ 
	cd Persistencia\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\Persistencia\Persistencia.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-Persistencia: Persistencia\$(MAKEFILE) FORCE
	cd Persistencia\ && $(MAKE) -f $(MAKEFILE)
sub-Persistencia-make_default: Persistencia\$(MAKEFILE) FORCE
	cd Persistencia\ && $(MAKE) -f $(MAKEFILE) 
sub-Persistencia-make_first: Persistencia\$(MAKEFILE) FORCE
	cd Persistencia\ && $(MAKE) -f $(MAKEFILE) first
sub-Persistencia-all: Persistencia\$(MAKEFILE) FORCE
	cd Persistencia\ && $(MAKE) -f $(MAKEFILE) all
sub-Persistencia-clean: Persistencia\$(MAKEFILE) FORCE
	cd Persistencia\ && $(MAKE) -f $(MAKEFILE) clean
sub-Persistencia-distclean: Persistencia\$(MAKEFILE) FORCE
	cd Persistencia\ && $(MAKE) -f $(MAKEFILE) distclean
sub-Persistencia-install_subtargets: Persistencia\$(MAKEFILE) FORCE
	cd Persistencia\ && $(MAKE) -f $(MAKEFILE) install
sub-Persistencia-uninstall_subtargets: Persistencia\$(MAKEFILE) FORCE
	cd Persistencia\ && $(MAKE) -f $(MAKEFILE) uninstall
Basico\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Basico\ $(MKDIR) Basico\ 
	cd Basico\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\Basico\Basico.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-Basico-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Basico\ $(MKDIR) Basico\ 
	cd Basico\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\Basico\Basico.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-Basico: Basico\$(MAKEFILE) FORCE
	cd Basico\ && $(MAKE) -f $(MAKEFILE)
sub-Basico-make_default: Basico\$(MAKEFILE) FORCE
	cd Basico\ && $(MAKE) -f $(MAKEFILE) 
sub-Basico-make_first: Basico\$(MAKEFILE) FORCE
	cd Basico\ && $(MAKE) -f $(MAKEFILE) first
sub-Basico-all: Basico\$(MAKEFILE) FORCE
	cd Basico\ && $(MAKE) -f $(MAKEFILE) all
sub-Basico-clean: Basico\$(MAKEFILE) FORCE
	cd Basico\ && $(MAKE) -f $(MAKEFILE) clean
sub-Basico-distclean: Basico\$(MAKEFILE) FORCE
	cd Basico\ && $(MAKE) -f $(MAKEFILE) distclean
sub-Basico-install_subtargets: Basico\$(MAKEFILE) FORCE
	cd Basico\ && $(MAKE) -f $(MAKEFILE) install
sub-Basico-uninstall_subtargets: Basico\$(MAKEFILE) FORCE
	cd Basico\ && $(MAKE) -f $(MAKEFILE) uninstall
ModuloInventario\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ModuloInventario\ $(MKDIR) ModuloInventario\ 
	cd ModuloInventario\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\ModuloInventario\ModuloInventario.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-ModuloInventario-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ModuloInventario\ $(MKDIR) ModuloInventario\ 
	cd ModuloInventario\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\ModuloInventario\ModuloInventario.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-ModuloInventario: ModuloInventario\$(MAKEFILE) FORCE
	cd ModuloInventario\ && $(MAKE) -f $(MAKEFILE)
sub-ModuloInventario-make_default: ModuloInventario\$(MAKEFILE) FORCE
	cd ModuloInventario\ && $(MAKE) -f $(MAKEFILE) 
sub-ModuloInventario-make_first: ModuloInventario\$(MAKEFILE) FORCE
	cd ModuloInventario\ && $(MAKE) -f $(MAKEFILE) first
sub-ModuloInventario-all: ModuloInventario\$(MAKEFILE) FORCE
	cd ModuloInventario\ && $(MAKE) -f $(MAKEFILE) all
sub-ModuloInventario-clean: ModuloInventario\$(MAKEFILE) FORCE
	cd ModuloInventario\ && $(MAKE) -f $(MAKEFILE) clean
sub-ModuloInventario-distclean: ModuloInventario\$(MAKEFILE) FORCE
	cd ModuloInventario\ && $(MAKE) -f $(MAKEFILE) distclean
sub-ModuloInventario-install_subtargets: ModuloInventario\$(MAKEFILE) FORCE
	cd ModuloInventario\ && $(MAKE) -f $(MAKEFILE) install
sub-ModuloInventario-uninstall_subtargets: ModuloInventario\$(MAKEFILE) FORCE
	cd ModuloInventario\ && $(MAKE) -f $(MAKEFILE) uninstall
ModuloCatalogo\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ModuloCatalogo\ $(MKDIR) ModuloCatalogo\ 
	cd ModuloCatalogo\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\ModuloCatalogo\ModuloCatalogo.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-ModuloCatalogo-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ModuloCatalogo\ $(MKDIR) ModuloCatalogo\ 
	cd ModuloCatalogo\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\ModuloCatalogo\ModuloCatalogo.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-ModuloCatalogo: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE)
sub-ModuloCatalogo-make_default: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) 
sub-ModuloCatalogo-make_first: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) first
sub-ModuloCatalogo-all: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) all
sub-ModuloCatalogo-clean: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) clean
sub-ModuloCatalogo-distclean: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) distclean
sub-ModuloCatalogo-install_subtargets: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) install
sub-ModuloCatalogo-uninstall_subtargets: ModuloCatalogo\$(MAKEFILE) FORCE
	cd ModuloCatalogo\ && $(MAKE) -f $(MAKEFILE) uninstall
ModuloContable\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) ModuloContable\ $(MKDIR) ModuloContable\ 
	cd ModuloContable\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\ModuloContable\ModuloContable.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-ModuloContable-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) ModuloContable\ $(MKDIR) ModuloContable\ 
	cd ModuloContable\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\ModuloContable\ModuloContable.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-ModuloContable: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE)
sub-ModuloContable-make_default: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) 
sub-ModuloContable-make_first: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) first
sub-ModuloContable-all: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) all
sub-ModuloContable-clean: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) clean
sub-ModuloContable-distclean: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) distclean
sub-ModuloContable-install_subtargets: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) install
sub-ModuloContable-uninstall_subtargets: ModuloContable\$(MAKEFILE) FORCE
	cd ModuloContable\ && $(MAKE) -f $(MAKEFILE) uninstall
SIBCUES-GUI\$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) SIBCUES-GUI\ $(MKDIR) SIBCUES-GUI\ 
	cd SIBCUES-GUI\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\SIBCUES-GUI\SIBCUES-GUI.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-SIBCUES-GUI-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) SIBCUES-GUI\ $(MKDIR) SIBCUES-GUI\ 
	cd SIBCUES-GUI\ && $(QMAKE) c:\Documents and Settings\Angelical.ANGELICAL_V4\Escritorio\SI-BCUES\SIBCUES-GUI\SIBCUES-GUI.pro -spec c:\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o $(MAKEFILE)
sub-SIBCUES-GUI: SIBCUES-GUI\$(MAKEFILE) FORCE
	cd SIBCUES-GUI\ && $(MAKE) -f $(MAKEFILE)
sub-SIBCUES-GUI-make_default: SIBCUES-GUI\$(MAKEFILE) FORCE
	cd SIBCUES-GUI\ && $(MAKE) -f $(MAKEFILE) 
sub-SIBCUES-GUI-make_first: SIBCUES-GUI\$(MAKEFILE) FORCE
	cd SIBCUES-GUI\ && $(MAKE) -f $(MAKEFILE) first
sub-SIBCUES-GUI-all: SIBCUES-GUI\$(MAKEFILE) FORCE
	cd SIBCUES-GUI\ && $(MAKE) -f $(MAKEFILE) all
sub-SIBCUES-GUI-clean: SIBCUES-GUI\$(MAKEFILE) FORCE
	cd SIBCUES-GUI\ && $(MAKE) -f $(MAKEFILE) clean
sub-SIBCUES-GUI-distclean: SIBCUES-GUI\$(MAKEFILE) FORCE
	cd SIBCUES-GUI\ && $(MAKE) -f $(MAKEFILE) distclean
sub-SIBCUES-GUI-install_subtargets: SIBCUES-GUI\$(MAKEFILE) FORCE
	cd SIBCUES-GUI\ && $(MAKE) -f $(MAKEFILE) install
sub-SIBCUES-GUI-uninstall_subtargets: SIBCUES-GUI\$(MAKEFILE) FORCE
	cd SIBCUES-GUI\ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: SI-BCUES.pro  ../../../../Qt/2010.04/qt/mkspecs/win32-g++/qmake.conf ../../../../Qt/2010.04/qt/mkspecs/qconfig.pri \
		../../../../Qt/2010.04/qt/mkspecs/features/qt_functions.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/qt_config.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/default_pre.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/win32/default_pre.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/release.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/debug_and_release.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/default_post.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/win32/default_post.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/win32/rtti.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/win32/exceptions.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/win32/stl.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/shared.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/warn_on.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/qt.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/win32/thread.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/moc.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/win32/windows.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/resources.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/uic.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/yacc.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/lex.prf \
		../../../../Qt/2010.04/qt/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ..\..\..\..\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o Makefile SI-BCUES.pro
..\..\..\..\Qt\2010.04\qt\mkspecs\qconfig.pri:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\qt_functions.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\qt_config.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\exclusive_builds.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\default_pre.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\win32\default_pre.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\release.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\debug_and_release.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\default_post.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\win32\default_post.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\win32\rtti.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\win32\exceptions.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\win32\stl.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\shared.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\warn_on.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\qt.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\win32\thread.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\moc.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\win32\windows.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\resources.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\uic.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\yacc.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\lex.prf:
..\..\..\..\Qt\2010.04\qt\mkspecs\features\include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec ..\..\..\..\Qt\2010.04\qt\mkspecs\win32-g++ -win32 CONFIG+=release -o Makefile SI-BCUES.pro

qmake_all: sub-Persistencia-qmake_all sub-Basico-qmake_all sub-ModuloInventario-qmake_all sub-ModuloCatalogo-qmake_all sub-ModuloContable-qmake_all sub-SIBCUES-GUI-qmake_all FORCE

make_default: sub-Persistencia-make_default sub-Basico-make_default sub-ModuloInventario-make_default sub-ModuloCatalogo-make_default sub-ModuloContable-make_default sub-SIBCUES-GUI-make_default FORCE
make_first: sub-Persistencia-make_first sub-Basico-make_first sub-ModuloInventario-make_first sub-ModuloCatalogo-make_first sub-ModuloContable-make_first sub-SIBCUES-GUI-make_first FORCE
all: sub-Persistencia-all sub-Basico-all sub-ModuloInventario-all sub-ModuloCatalogo-all sub-ModuloContable-all sub-SIBCUES-GUI-all FORCE
clean: sub-Persistencia-clean sub-Basico-clean sub-ModuloInventario-clean sub-ModuloCatalogo-clean sub-ModuloContable-clean sub-SIBCUES-GUI-clean FORCE
distclean: sub-Persistencia-distclean sub-Basico-distclean sub-ModuloInventario-distclean sub-ModuloCatalogo-distclean sub-ModuloContable-distclean sub-SIBCUES-GUI-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-Persistencia-install_subtargets sub-Basico-install_subtargets sub-ModuloInventario-install_subtargets sub-ModuloCatalogo-install_subtargets sub-ModuloContable-install_subtargets sub-SIBCUES-GUI-install_subtargets FORCE
uninstall_subtargets: sub-Persistencia-uninstall_subtargets sub-Basico-uninstall_subtargets sub-ModuloInventario-uninstall_subtargets sub-ModuloCatalogo-uninstall_subtargets sub-ModuloContable-uninstall_subtargets sub-SIBCUES-GUI-uninstall_subtargets FORCE

sub-Persistencia-sub_Debug: Persistencia\$(MAKEFILE)
	cd Persistencia\ && $(MAKE) debug
sub-Basico-sub_Debug: Basico\$(MAKEFILE)
	cd Basico\ && $(MAKE) debug
sub-ModuloInventario-sub_Debug: ModuloInventario\$(MAKEFILE)
	cd ModuloInventario\ && $(MAKE) debug
sub-ModuloCatalogo-sub_Debug: ModuloCatalogo\$(MAKEFILE)
	cd ModuloCatalogo\ && $(MAKE) debug
sub-ModuloContable-sub_Debug: ModuloContable\$(MAKEFILE)
	cd ModuloContable\ && $(MAKE) debug
sub-SIBCUES-GUI-sub_Debug: SIBCUES-GUI\$(MAKEFILE)
	cd SIBCUES-GUI\ && $(MAKE) debug
debug: sub-Persistencia-sub_Debug sub-Basico-sub_Debug sub-ModuloInventario-sub_Debug sub-ModuloCatalogo-sub_Debug sub-ModuloContable-sub_Debug sub-SIBCUES-GUI-sub_Debug

sub-Persistencia-sub_Release: Persistencia\$(MAKEFILE)
	cd Persistencia\ && $(MAKE) release
sub-Basico-sub_Release: Basico\$(MAKEFILE)
	cd Basico\ && $(MAKE) release
sub-ModuloInventario-sub_Release: ModuloInventario\$(MAKEFILE)
	cd ModuloInventario\ && $(MAKE) release
sub-ModuloCatalogo-sub_Release: ModuloCatalogo\$(MAKEFILE)
	cd ModuloCatalogo\ && $(MAKE) release
sub-ModuloContable-sub_Release: ModuloContable\$(MAKEFILE)
	cd ModuloContable\ && $(MAKE) release
sub-SIBCUES-GUI-sub_Release: SIBCUES-GUI\$(MAKEFILE)
	cd SIBCUES-GUI\ && $(MAKE) release
release: sub-Persistencia-sub_Release sub-Basico-sub_Release sub-ModuloInventario-sub_Release sub-ModuloCatalogo-sub_Release sub-ModuloContable-sub_Release sub-SIBCUES-GUI-sub_Release

sub-Persistencia-check: Persistencia\$(MAKEFILE)
	cd Persistencia\ && $(MAKE) check
sub-Basico-check: Basico\$(MAKEFILE)
	cd Basico\ && $(MAKE) check
sub-ModuloInventario-check: ModuloInventario\$(MAKEFILE)
	cd ModuloInventario\ && $(MAKE) check
sub-ModuloCatalogo-check: ModuloCatalogo\$(MAKEFILE)
	cd ModuloCatalogo\ && $(MAKE) check
sub-ModuloContable-check: ModuloContable\$(MAKEFILE)
	cd ModuloContable\ && $(MAKE) check
sub-SIBCUES-GUI-check: SIBCUES-GUI\$(MAKEFILE)
	cd SIBCUES-GUI\ && $(MAKE) check
check: sub-Persistencia-check sub-Basico-check sub-ModuloInventario-check sub-ModuloCatalogo-check sub-ModuloContable-check sub-SIBCUES-GUI-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

