#ifndef MODULOINVENTARIO_GLOBAL_H
#define MODULOINVENTARIO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULOINVENTARIO_LIBRARY)
#  define MODULOINVENTARIOSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULOINVENTARIOSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULOINVENTARIO_GLOBAL_H
