#ifndef MODULOCONTABLE_GLOBAL_H
#define MODULOCONTABLE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULOCONTABLE_LIBRARY)
#  define MODULOCONTABLESHARED_EXPORT Q_DECL_EXPORT
#else
#define MODULOCONTABLESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULOCONTABLE_GLOBAL_H
